spring:
  application:
    name: feeda

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  error:
    include-message: always

jwt:
  secret:
    key: ${SECRET_KEY}
