spring:
  application:
    name: feeda

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

server:
  error:
    include-message: always

#  logging.level.org.springframework.security = trace

jwt:
  secret:
    key: enfih1329hs9dvalwmEJib31agea3131tgfsahsj6jwaw4gr80gkjsnoefnqldc


logging:
  level:
    org:
      springframework:
        security: trace