spring:
  application:
    name: feeda

  datasource:
    url: jdbc:mysql://localhost:3306/${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

server:
  error:
    include-message: always

jwt:
  secret:
    key: ${SECRET_KEY}